import { useEffect, useMemo, useState } from "react";
import {
  Inbox,
  RefreshCw,
  Download,
  ChevronUp,
  ChevronDown,
  ChevronsLeft,
  ChevronsRight,
  Settings2,
  FileSpreadsheet,
  Users,
} from "lucide-react";
import * as XLSX from "xlsx";
import { useAuth } from "../../context/AuthContext";
import BarChart from "../../components/common/BarChart";
import {
  REPORT_TYPES,
  loadReportData,
  getAvailableYears,
  getMonthlyPatientCounts,
  getYearlyPatientCounts,
  getDiagnosisBreakdown,
  getIcd10DiagnosisReportRows,
  getReportRows,
  loadReports,
  addReport,
  generateReportId,
} from "../../utils/reports";

const ALL_COLUMNS = [
  { id: "reportType", label: "Report Type", pinned: true },
  { id: "year", label: "Year" },
  { id: "generated", label: "Generated" },
  { id: "generatedBy", label: "Generated By" },
  { id: "status", label: "Status" },
];

function StatusBadge({ status }) {
  const isCompleted = status === "Completed";
  return (
    <span
      className={`inline-block px-2.5 py-1 rounded-full text-[11px] font-semibold uppercase tracking-wide ${
        isCompleted ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"
      }`}
    >
      {status}
    </span>
  );
}

function SortHeader({ label, sortKey, sort, onSort }) {
  const active = sort.key === sortKey;
  return (
    <button
      type="button"
      onClick={() => onSort(sortKey)}
      className="inline-flex items-center gap-1 hover:text-white transition-colors"
    >
      {label}
      {active ? (
        sort.dir === "asc" ? <ChevronUp size={12} /> : <ChevronDown size={12} />
      ) : (
        <span className="flex flex-col -space-y-1 opacity-50">
          <ChevronUp size={10} />
          <ChevronDown size={10} />
        </span>
      )}
    </button>
  );
}

function formatDateTime(iso) {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleString("en-PH", {
    month: "2-digit",
    day: "2-digit",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

// Builds and downloads an .xlsx from an array of plain objects.
function downloadExcel(rows, filename, sheetName = "Sheet1") {
  const worksheet = XLSX.utils.json_to_sheet(rows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  XLSX.writeFile(workbook, filename);
}

export default function Reports() {
  const { user } = useAuth();

  const [reportType, setReportType] = useState("");
  const [year, setYear] = useState(String(new Date().getFullYear()));
  const [generating, setGenerating] = useState(false);
  const [preview, setPreview] = useState(null);

  const [reports, setReports] = useState(() => loadReports());
  const [activeTypeTab, setActiveTypeTab] = useState("All Reports");
  const [tableYear, setTableYear] = useState("All");

  const [reportData, setReportData] = useState({ patients: [], consultations: [] });
  const [dataLoading, setDataLoading] = useState(true);
  const { patients, consultations } = reportData;

  const [sort, setSort] = useState({ key: "generated", dir: "desc" });
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const [showColumnConfig, setShowColumnConfig] = useState(false);
  const [visibleColumns, setVisibleColumns] = useState(
    Object.fromEntries(ALL_COLUMNS.map((c) => [c.id, true]))
  );

  const availableYears = useMemo(() => getAvailableYears(), []);
  const graphYear = tableYear !== "All" ? tableYear : availableYears[0];
  const monthlyPatientData = useMemo(() => getMonthlyPatientCounts(graphYear), [graphYear, reports]);
  const yearlyPatientData = useMemo(() => getYearlyPatientCounts(), [reports]);

  function refresh() {
    setReports(loadReports());
  }

  function handleGenerate() {
    if (!reportType || !year) return;
    setGenerating(true);
    setPreview(null);
    setTimeout(() => {
      const rows = getReportRows(reportType, year);
      const report = {
        id: generateReportId(),
        reportType,
        year,
        generatedAt: new Date().toISOString(),
        generatedBy: user?.username || "Unknown",
        status: "Completed",
        rowCount: rows.length,
      };
      addReport(report);
      setReports(loadReports());
      setPreview({ ...report, rows });
      setGenerating(false);
    }, 700);
  }

  function handleSort(key) {
    setSort((prev) => (prev.key === key ? { key, dir: prev.dir === "asc" ? "desc" : "asc" } : { key, dir: "asc" }));
  }

  const typeTabs = useMemo(() => {
    const present = Array.from(new Set(reports.map((r) => r.reportType)));
    return ["All Reports", ...present];
  }, [reports]);

  const filteredReports = useMemo(() => {
    let list = [...reports];
    if (activeTypeTab !== "All Reports") list = list.filter((r) => r.reportType === activeTypeTab);
    if (tableYear !== "All") list = list.filter((r) => String(r.year) === String(tableYear));

    list.sort((a, b) => {
      const dir = sort.dir === "asc" ? 1 : -1;
      if (sort.key === "generated") return (new Date(a.generatedAt) - new Date(b.generatedAt)) * dir;
      if (sort.key === "year") return (Number(a.year) - Number(b.year)) * dir;
      return String(a[sort.key] || "").localeCompare(String(b[sort.key] || "")) * dir;
    });
    return list;
  }, [reports, activeTypeTab, tableYear, sort]);

  const totalPages = Math.max(1, Math.ceil(filteredReports.length / pageSize));
  const pagedReports = filteredReports.slice((page - 1) * pageSize, page * pageSize);

  useEffect(() => {
    setPage(1);
  }, [activeTypeTab, tableYear, pageSize]);

  function handleDownloadRow(report) {
    const rows = getReportRows(report.reportType, report.year);
    if (rows.length === 0) {
      window.alert("This report has no rows to export.");
      return;
    }
    downloadExcel(
      rows,
      `${report.reportType.replace(/\s+/g, "_")}_${report.year}.xlsx`,
      report.reportType.slice(0, 30)
    );
  }

  function handleDownloadAll() {
    if (reports.length === 0) {
      window.alert("There are no generated reports to export yet.");
      return;
    }
    const rows = reports.map((r) => ({
      "Report Type": r.reportType,
      Year: r.year,
      Generated: formatDateTime(r.generatedAt),
      "Generated By": r.generatedBy,
      Status: r.status,
      "Row Count": r.rowCount,
    }));
    downloadExcel(rows, "All_Reports.xlsx", "Reports");
  }

  return (
    <div className="max-w-[1400px]">
      <div className="flex items-start justify-between mb-5">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Reports</h1>
          <p className="text-sm text-slate-500 mt-0.5">Generate and download reports</p>
        </div>
        <div className="relative">
          <button
            type="button"
            onClick={() => setShowColumnConfig((s) => !s)}
            className="inline-flex items-center gap-1.5 rounded-lg bg-blue-700 hover:bg-blue-800 text-white px-4 py-2 text-sm font-medium shadow-sm transition-colors"
          >
            <Settings2 size={15} />
            Configure Columns
          </button>
          {showColumnConfig && (
            <div className="absolute right-0 mt-1 w-52 bg-white border border-slate-200 rounded-lg shadow-lg z-20 p-2">
              <p className="text-[11px] font-semibold uppercase text-slate-400 px-2 py-1">Table Columns</p>
              {ALL_COLUMNS.filter((c) => !c.pinned).map((c) => (
                <label
                  key={c.id}
                  className="flex items-center gap-2 px-2 py-1.5 text-sm text-slate-700 hover:bg-slate-50 rounded-md cursor-pointer"
                >
                  <input
                    type="checkbox"
                    checked={visibleColumns[c.id]}
                    onChange={() => setVisibleColumns((v) => ({ ...v, [c.id]: !v[c.id] }))}
                    className="rounded border-slate-300 text-teal-700 focus:ring-teal-600"
                  />
                  {c.label}
                </label>
              ))}
            </div>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-4">
          <p className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-1.5">
            <Users size={15} className="text-teal-700" />
            Patients Registered Monthly — {graphYear || "—"}
          </p>
          <BarChart data={monthlyPatientData} color="#7c3aed" emptyLabel="No patients registered this year yet" />
        </div>
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-4">
          <p className="text-sm font-semibold text-slate-700 mb-3 flex items-center gap-1.5">
            <Users size={15} className="text-teal-700" />
            Patients Registered Yearly
          </p>
          <BarChart data={yearlyPatientData} color="#c026d3" emptyLabel="No patients registered yet" />
        </div>
      </div>

      <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-5 mb-5">
        <p className="text-sm font-bold text-slate-800 mb-4">Generate New Report</p>
        <div className="flex flex-col md:flex-row gap-4 items-end">
          <div className="flex-1 w-full">
            <label className="text-xs font-semibold text-slate-600 mb-1 block">
              Report Type <span className="text-red-500">*</span>
            </label>
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-600 focus:border-teal-600"
            >
              <option value="">Select report type</option>
              {REPORT_TYPES.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </div>
          <div className="flex-1 w-full">
            <label className="text-xs font-semibold text-slate-600 mb-1 block">
              Year <span className="text-red-500">*</span>
            </label>
            <select
              value={year}
              onChange={(e) => setYear(e.target.value)}
              className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-600 focus:border-teal-600"
            >
              {availableYears.map((y) => (
                <option key={y} value={y}>
                  {y}
                </option>
              ))}
            </select>
          </div>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={!reportType || !year || generating}
            className="rounded-lg bg-teal-700 hover:bg-teal-800 disabled:opacity-50 text-white text-sm font-semibold px-5 py-2 shadow-sm transition-colors shrink-0"
          >
            {generating ? "Generating…" : "Generate Report"}
          </button>
        </div>
      </div>

      {generating ? (
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-10 flex flex-col items-center justify-center text-center mb-5">
          <RefreshCw size={26} className="text-teal-600 animate-spin mb-2" />
          <p className="text-sm text-slate-500">Generating your report…</p>
        </div>
      ) : preview ? (
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-5 mb-5">
          <div className="flex items-center justify-between mb-4">
            <div>
              <p className="text-sm font-bold text-slate-800">
                {preview.reportType} — {preview.year}
              </p>
              <p className="text-xs text-slate-500">{preview.rowCount} record(s) found</p>
            </div>
            <button
              type="button"
              onClick={() => handleDownloadRow(preview)}
              className="inline-flex items-center gap-1.5 rounded-lg border border-teal-700 text-teal-700 hover:bg-teal-50 px-3 py-1.5 text-xs font-semibold transition-colors"
            >
              <Download size={13} />
              Download Excel
            </button>
          </div>

          {preview.reportType === "Diagnosis Report" && (
            <div className="mb-4">
              <BarChart
                data={getDiagnosisBreakdown(preview.year)
                  .slice(0, 8)
                  .map((d) => ({ label: d.label, value: d.count }))}
                color="#b45309"
                emptyLabel="No diagnoses recorded for this year yet"
              />
            </div>
          )}

          {preview.reportType === "ICD-10 Diagnosis Report" && (
            <div className="mb-4">
              <BarChart
                data={getIcd10DiagnosisReportRows(preview.year)
                  .slice(0, 8)
                  .map((d) => ({ label: `${d.code} — ${d.name}`, value: d.patientCount }))}
                color="#0f766e"
                emptyLabel="No coded diagnoses recorded for this year yet"
              />
            </div>
          )}

          {preview.rows.length === 0 ? (
            <p className="text-xs text-slate-400 text-center py-6">No records found for this selection.</p>
          ) : (
            <div className="overflow-x-auto border border-slate-100 rounded-lg">
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-slate-50 text-slate-500 uppercase text-[10px]">
                    {Object.keys(preview.rows[0]).map((key) => (
                      <th key={key} className="px-3 py-2 text-left whitespace-nowrap">
                        {key}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {preview.rows.slice(0, 25).map((row, i) => (
                    <tr key={i} className="border-t border-slate-100">
                      {Object.values(row).map((val, j) => (
                        <td key={j} className="px-3 py-2 text-slate-700 whitespace-nowrap">
                          {String(val ?? "—")}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
              {preview.rows.length > 25 && (
                <p className="text-[11px] text-slate-400 text-center py-2">
                  Showing first 25 of {preview.rows.length} — download the Excel file for the full list.
                </p>
              )}
            </div>
          )}
        </div>
      ) : (
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-10 flex flex-col items-center justify-center text-center mb-5">
          <Inbox size={30} className="text-slate-300 mb-2" />
          <p className="text-sm text-slate-500">No reports are currently being processed.</p>
        </div>
      )}

      <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden">
        <div className="flex items-center justify-between px-5 pt-4 pb-3 border-b border-slate-100">
          <p className="text-sm font-bold text-slate-800">Recent Reports</p>
          <button
            type="button"
            onClick={handleDownloadAll}
            className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-700 hover:bg-emerald-800 text-white px-3 py-1.5 text-xs font-semibold transition-colors"
          >
            <FileSpreadsheet size={13} />
            Download All (Excel)
          </button>
        </div>

        <div className="flex items-center justify-between px-5 py-3 gap-3 flex-wrap">
          <div className="flex items-center gap-2 flex-wrap">
            {typeTabs.map((tab) => (
              <button
                key={tab}
                type="button"
                onClick={() => setActiveTypeTab(tab)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${
                  activeTypeTab === tab
                    ? "bg-teal-700 text-white shadow-sm"
                    : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2">
            <select
              value={tableYear}
              onChange={(e) => setTableYear(e.target.value)}
              className="rounded-lg border border-slate-300 bg-white px-2.5 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-teal-600"
            >
              <option value="All">All Years</option>
              {availableYears.map((y) => (
                <option key={y} value={y}>
                  {y}
                </option>
              ))}
            </select>
            <button
              type="button"
              onClick={refresh}
              title="Refresh"
              className="w-8 h-8 rounded-lg border border-slate-300 text-slate-500 hover:bg-slate-50 flex items-center justify-center transition-colors"
            >
              <RefreshCw size={14} />
            </button>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-teal-800 text-white text-xs uppercase">
                <th className="px-4 py-3 text-left">
                  <SortHeader label="Report Type" sortKey="reportType" sort={sort} onSort={handleSort} />
                </th>
                {visibleColumns.year && (
                  <th className="px-4 py-3 text-left">
                    <SortHeader label="Year" sortKey="year" sort={sort} onSort={handleSort} />
                  </th>
                )}
                {visibleColumns.generated && (
                  <th className="px-4 py-3 text-left">
                    <SortHeader label="Generated" sortKey="generated" sort={sort} onSort={handleSort} />
                  </th>
                )}
                {visibleColumns.generatedBy && (
                  <th className="px-4 py-3 text-left">
                    <SortHeader label="Generated By" sortKey="generatedBy" sort={sort} onSort={handleSort} />
                  </th>
                )}
                {visibleColumns.status && (
                  <th className="px-4 py-3 text-left">
                    <SortHeader label="Status" sortKey="status" sort={sort} onSort={handleSort} />
                  </th>
                )}
                <th className="px-4 py-3 text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              {pagedReports.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-4 py-10 text-center text-sm text-slate-400">
                    No reports match this filter yet.
                  </td>
                </tr>
              ) : (
                pagedReports.map((r) => (
                  <tr key={r.id} className="border-t border-slate-100 hover:bg-slate-50">
                    <td className="px-4 py-3 font-medium text-slate-800">{r.reportType}</td>
                    {visibleColumns.year && <td className="px-4 py-3 text-slate-600">{r.year}</td>}
                    {visibleColumns.generated && (
                      <td className="px-4 py-3 text-slate-600">{formatDateTime(r.generatedAt)}</td>
                    )}
                    {visibleColumns.generatedBy && <td className="px-4 py-3 text-slate-600">{r.generatedBy}</td>}
                    {visibleColumns.status && (
                      <td className="px-4 py-3">
                        <StatusBadge status={r.status} />
                      </td>
                    )}
                    <td className="px-4 py-3">
                      <button
                        type="button"
                        onClick={() => handleDownloadRow(r)}
                        title="Download Excel"
                        className="w-8 h-8 rounded-lg bg-teal-700 hover:bg-teal-800 text-white flex items-center justify-center transition-colors"
                      >
                        <Download size={14} />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <div className="flex items-center justify-between px-5 py-3 border-t border-slate-100 text-xs text-slate-500">
          <p>
            Showing {filteredReports.length === 0 ? 0 : (page - 1) * pageSize + 1} to{" "}
            {Math.min(page * pageSize, filteredReports.length)} of {filteredReports.length} entries
          </p>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setPage(1)}
              disabled={page === 1}
              className="w-7 h-7 rounded-md border border-slate-200 disabled:opacity-40 flex items-center justify-center hover:bg-slate-50"
            >
              <ChevronsLeft size={13} />
            </button>
            <button
              type="button"
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page === 1}
              className="w-7 h-7 rounded-md border border-slate-200 disabled:opacity-40 flex items-center justify-center hover:bg-slate-50"
            >
              ‹
            </button>
            <span className="w-7 h-7 rounded-full bg-teal-100 text-teal-700 font-semibold flex items-center justify-center">
              {page}
            </span>
            <button
              type="button"
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page === totalPages}
              className="w-7 h-7 rounded-md border border-slate-200 disabled:opacity-40 flex items-center justify-center hover:bg-slate-50"
            >
              ›
            </button>
            <button
              type="button"
              onClick={() => setPage(totalPages)}
              disabled={page === totalPages}
              className="w-7 h-7 rounded-md border border-slate-200 disabled:opacity-40 flex items-center justify-center hover:bg-slate-50"
            >
              <ChevronsRight size={13} />
            </button>
            <select
              value={pageSize}
              onChange={(e) => setPageSize(Number(e.target.value))}
              className="rounded-md border border-slate-200 px-2 py-1 text-xs ml-1"
            >
              {[10, 25, 50].map((n) => (
                <option key={n} value={n}>
                  {n}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>
    </div>
  );
}